name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up rust
      uses: actions/set-rust@v1
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
